version: 2.1

workflows:
  main:
    jobs:
      - build-release:
          context: org-global

jobs:
  build-release:
    machine: true
    steps:
      - checkout
      - run:
          name: "Build Docker Images"
          command: docker build -t viaops/hugo:latest
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
            
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

              if git log -1 --pretty=%s | grep "\[release\]"; then
                echo "Starting a release"
                docker push viaops/hugo
              else
                echo "Publish the latest image"
                docker tag viaops/hugo:latest viaops/hugo
                docker push viaops/hugo
              fi
            fi
